server:
  port: 8081
spring:
  application:
    name: web
  redis:
      host: 172.168.11.108
      password: tykj_ncpzs
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

logging:
  level:
    root: info
  path: logs
#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://139.199.101.89:3306/LW?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: wangqiyue
  password: wangqiyue
  maxWait: 5000
  maxActive: 50
  removeAbandoned: true
  removeAbandonedTimeout: 180


#mybatis config
mybatis:
  typeAliasesPackage: com.lw
  mapperLocations: classpath:mapper/**/*.xml

snowflake:
  workerId: 0
  datacenterId: 0
