server:
  port: 8081
spring:
  application:
    name: web
  redis:
    host: 127.0.0.1
    pool:
      max-idle: 8
      min-idle: 0
#    port: 6380
    port: 6379
    password:
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

logging:
  level:
    root: info
  path: logs
#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/LW?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: wangqiyue
  password: wangqiyue
  maxWait: 5000
  maxActive: 50
  removeAbandoned: true
  removeAbandonedTimeout: 180


#mybatis config
mybatis:
  typeAliasesPackage: com.lw
  mapperLocations: classpath:mapper/**/*.xml

snowflake:
  workerId: 0
  datacenterId: 0
